"""Path builders for per-exam derived artifacts, organised by pipeline phase.

Sub-modules:

- :mod:`._helpers` — name normalisation, exam artifact roots, the standalone
  ``extract_answers`` tool's output directory.
- :mod:`.scan` — scan-side preprocessing (cover, geometry, subject, names,
  page order, handwriting).
- :mod:`.scaffold` — empty-exam structure detection + mark scheme (layout,
  exam questions, mark scheme, scaffold cache).
- :mod:`.marking` — marking pipeline outputs (parse_instructions, marking
  page register, blueprints, MCQ corrections, review queue).
- :mod:`.student` — student-keyed artifacts (roster, answers, reports, PDFs
  + layout variants).
- :mod:`.class_report` — class-level reporting (stats, report files, charts,
  scheme-graphics check).
- :mod:`.run_summary` — end-of-run summaries (timing, AI cost).

This package re-exports every public symbol so historical
``from xscore.shared.path_builders import …`` and
``from xscore.shared.exam_paths import …`` call sites continue to work.
"""

from xscore.shared.paths._helpers import (  # noqa: F401
    artifact_input_dir,
    exam_artifact_dir,
    extract_answers_output_dir,
    safe_path_stem,
    safe_student_name,
)
from xscore.shared.paths.class_report import (  # noqa: F401
    artifact_class_grade_histogram_curved_path,
    artifact_class_grade_histogram_raw_path,
    artifact_class_marks_xlsx_path,
    artifact_class_question_difficulty_path,
    artifact_class_question_difficulty_top_path,
    artifact_class_report_charts_dir,
    artifact_class_report_combined_landscape_pdf_path,
    artifact_class_report_combined_landscape_with_questions_pdf_path,
    artifact_class_report_combined_portrait_2up_pdf_path,
    artifact_class_report_combined_portrait_list_pdf_path,
    artifact_class_report_combined_portrait_pdf_path,
    artifact_class_report_dir,
    artifact_class_report_exam_questions_dir,
    artifact_class_report_landscape_dir,
    artifact_class_report_md_path,
    artifact_class_report_pdf_2up_path,
    artifact_class_report_pdf_path,
    artifact_class_report_portrait_dir,
    artifact_class_report_scheme_graphics_check_dir,
    artifact_class_report_summary_dir,
    artifact_class_report_tex_path,
    artifact_class_report_xml_path,
    artifact_class_stats_json_path,
    artifact_exam_questions_pdf_path,
    artifact_exam_questions_tex_path,
    artifact_scheme_graphics_check_pdf_path,
    artifact_scheme_graphics_check_tex_path,
)
from xscore.shared.paths.marking import (  # noqa: F401
    artifact_blueprint_json_path,
    artifact_blueprint_md_path,
    artifact_blueprint_path,
    artifact_blueprint_xml_path,
    artifact_continuation_refs_json_path,
    artifact_cross_page_changes_md_path,
    artifact_cross_page_refs_json_path,
    artifact_marking_page_register_v1_path,
    artifact_marking_page_register_v2_path,
    artifact_mcq_corrections_path,
    artifact_parent_refs_json_path,
    artifact_parse_prompt_path,
    artifact_parse_summary_path,
    artifact_review_queue_json_path,
    artifact_review_queue_md_path,
    artifact_review_queue_txt_path,
)
from xscore.shared.paths.run_summary import (  # noqa: F401
    artifact_cost_json_path,
    artifact_cost_md_path,
    artifact_timing_json_path,
    artifact_timing_md_path,
)
from xscore.shared.paths.scaffold import (  # noqa: F401
    artifact_cover_page_dir,
    artifact_empty_exam_classifications_json_path,
    artifact_empty_exam_pages_dir,
    artifact_exam_input_pdf_path,
    artifact_exam_layout_json_path,
    artifact_exam_layout_markdown_path,
    artifact_exam_layout_raw_path,
    artifact_exam_layout_xml_path,
    artifact_exam_pages_dir,
    artifact_exam_questions_json_path,
    artifact_exam_questions_markdown_path,
    artifact_exam_questions_path,
    artifact_exam_questions_raw_path,
    artifact_exam_questions_raw_xml_path,
    artifact_exam_questions_xml_path,
    artifact_exam_scaffold_path,
    artifact_exam_scaffold_raw_path,
    artifact_mark_scheme_graphics_dir,
    artifact_mark_scheme_graphics_yaml_path,
    artifact_mark_scheme_json_path,
    artifact_mark_scheme_markdown_path,
    artifact_mark_scheme_path,
    artifact_mark_scheme_pages_dir,
    artifact_mark_scheme_xml_path,
    artifact_questions_per_page_path,
    artifact_scaffold_json_path,
    artifact_scaffold_markdown_path,
    artifact_scaffold_prompt_path,
    artifact_scaffold_xml_path,
    artifact_scaffold_yaml_path,
    artifact_scheme_graphic_transcriptions_path,
    artifact_short_scaffold_json_path,
    artifact_short_scaffold_markdown_path,
    artifact_split_exam_pdf_path,
    find_scaffold_cache_file,
    is_completed_run,
)
from xscore.shared.paths.scan import (  # noqa: F401
    artifact_cover_scan_prompt_path,
    artifact_exam_page_range_overview_path,
    artifact_exam_student_list_json_path,
    artifact_exam_student_list_md_path,
    artifact_geometry_json_path,
    artifact_geometry_md_path,
    artifact_geometry_prompt_path,
    artifact_handwriting_dir,
    artifact_handwriting_json_path,
    artifact_handwriting_prompt_path,
    artifact_names_prompt_path,
    artifact_page_order_empty_exam_txt_path,
    artifact_page_order_issues_path,
    artifact_page_order_txt_path,
    artifact_subject_dir,
    artifact_subject_json_path,
    artifact_subject_md_path,
    artifact_subject_prompt_path,
)
from xscore.shared.paths.student import (  # noqa: F401
    artifact_marked_failed_path,
    artifact_marked_md_path,
    artifact_marked_path,
    artifact_marking_prompt_path,
    artifact_marking_students_dir,
    artifact_reports_students_dir,
    artifact_student_answers_dir,
    artifact_student_answers_failed_path,
    artifact_student_answers_path,
    artifact_student_answers_prompt_path,
    artifact_student_list_prompt_path,
    artifact_student_pdf_dir,
    artifact_student_pdf_variant_dir,
    artifact_student_pdfs_dir,
    artifact_student_report_dir,
    artifact_student_report_md_attempted_path,
    artifact_student_report_md_path,
    artifact_student_report_pdf_landscape_attempted_path,
    artifact_student_report_pdf_landscape_path,
    artifact_student_report_pdf_landscape_with_questions_attempted_path,
    artifact_student_report_pdf_landscape_with_questions_path,
    artifact_student_report_pdf_portrait_2up_attempted_path,
    artifact_student_report_pdf_portrait_2up_path,
    artifact_student_report_pdf_portrait_attempted_path,
    artifact_student_report_pdf_portrait_large_attempted_path,
    artifact_student_report_pdf_portrait_large_path,
    artifact_student_report_pdf_portrait_list_attempted_path,
    artifact_student_report_pdf_portrait_list_path,
    artifact_student_report_pdf_portrait_path,
    artifact_student_report_tex_landscape_attempted_path,
    artifact_student_report_tex_landscape_path,
    artifact_student_report_tex_landscape_with_questions_attempted_path,
    artifact_student_report_tex_landscape_with_questions_path,
    artifact_student_report_tex_portrait_attempted_path,
    artifact_student_report_tex_portrait_large_attempted_path,
    artifact_student_report_tex_portrait_large_path,
    artifact_student_report_tex_portrait_list_attempted_path,
    artifact_student_report_tex_portrait_list_path,
    artifact_student_report_tex_portrait_path,
    artifact_student_report_yaml_path,
    artifact_student_reports_dir,
    artifact_students_json_path,
    artifact_students_markdown_path,
)
